#spring:
#  datasource:
#    url: jdbc:mysql://mysql.cwcmryyk9nvs.ap-northeast-2.rds.amazonaws.com:3306/saessak_java?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: saessakjava
#    password: saessak1004
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        use-new-id-generator-mappings: false
#        default_batch_fetch_size: 100
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#
#logging.level:
#  org.hibernate.SQL: debug

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/saessak
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK